/**
 * Embedded trust anchor for dispatch verification.
 *
 * ROOT_PUBKEY_HEX is the ONLY key baked into the package. It does not sign
 * dispatches — it signs the rotatable key set served at
 * GET /api/codewriter/jwks (see keyset.ts). Dispatch-signing keys can
 * therefore be rotated (or revoked after a leak) by republishing the signed
 * key set, with no npm release and no daemon update.
 *
 * The corresponding root private key lives OFFLINE (generated by
 * `npm run keys:init`, used only by `npm run keys:rotate`). It must never be
 * deployed to the server: a compromised server then still can't mint keys the
 * daemon would trust.
 *
 * Rotating the ROOT key itself does require an npm republish — by design,
 * it's the tradeoff that makes everything else rotatable.
 */

/** Production root public key (Ed25519, 32 bytes, hex). */
export const ROOT_PUBKEY_HEX =
  '354d74db4f7cd284ba972665c76828836420aa40e2a03968340b398bfbdd24cb';

/**
 * Dev/test public key — used by daemon-stub.ts and tests ONLY (injected
 * explicitly; never part of the production trust path).
 * Generated deterministically for test fixtures:
 *   privKey = 0x00...01 (for test only, NOT secure)
 */
export const DEV_PUBKEY_HEX =
  '4cb5abf6ad79fbf5abbccafcc269d85cd2651ed4b885b5869f241aedf0a5ba29';

/**
 * Legacy static-key fallback. Returns [] — production verification goes
 * through the kid-based KeysetClient (keyset.ts); a caller that reaches this
 * fallback has no trusted keys and rejects everything, which is the safe
 * default.
 */
export function getTrustedPubkeys(): string[] {
  return [];
}

/**
 * Returns trusted keys for dev/test mode.
 */
export function getDevPubkeys(): string[] {
  return [DEV_PUBKEY_HEX];
}
